blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

mi:
    resource: "@MiBundle/Resources/config/routing.yml"
    prefix:   /

rutas_bundle:
    resource: "@AppBundle/Resources/config/routes.yml"
    prefix: /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
