BlogBundle\Entity\Tags:
  properties:
    name: 
        - NotBlank: {message: "El nombre no puede estar vacio"}
        - Length: 
            min: 2
            minMessage: "El nombre tiene que tener mas de 2 caracteres"